---
name: Update cmd repositories
on:
  push:
    branches:
      - master

jobs:
  update-cmd-repositories:
    strategy:
      matrix:
        repository: [cmd-registry-proxy-dns]
    name: Update ${{ matrix.repository }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: ${{ github.repository }}
          repository: ${{ github.repository }}
          token: ${{ secrets.NSM_BOT_GITHUB_TOKEN }}
      - name: Find merged PR
        uses: jwalton/gh-find-current-pr@v1
        id: findPr
        with:
          github-token: ${{ github.token }}
      - name: Create commit message
        working-directory: ${{ github.repository }}
        run: |
          echo "Update common CI files to latest version from ${{ github.repository }}@master ${{ github.repository }}#${{ steps.findPr.outputs.pr }}" >> /tmp/commit-message
          echo "" >> /tmp/commit-message
          echo "${{ github.repository }} PR link: https://github.com/${{ github.repository }}/pull/${{ steps.findPr.outputs.pr }}" >> /tmp/commit-message
          echo "" >> /tmp/commit-message
          echo "${{ github.repository }} commit message:" >> /tmp/commit-message
          git log -1 >> /tmp/commit-message
          echo "Commit Message:"
          cat /tmp/commit-message
      - uses: actions/checkout@v2
        with:
          path: networkservicemesh/${{ matrix.repository }}
          repository: networkservicemesh/${{ matrix.repository }}
          token: ${{ secrets.NSM_BOT_GITHUB_TOKEN }}
          sha: ${{ GITHUB_SHA }}
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13.4
      - name: Push update to ${{ matrix.repository }}
        working-directory: networkservicemesh/${{ matrix.repository }}
        run: |
          git config --global user.email "nsmbot@networkservicmesh.io"
          git config --global user.name "NSMBot"
          git remote add cmd_template https://github.com/networkservicemesh/cmd-template.git
          git fetch cmd_template
          git cherry-pick --no-commit ${sha}
          git commit -F /tmp/commit-message
          git checkout -b update/sdk-gomod
          git push -f origin update/sdk-gomod